# Generated by Django 3.0.6 on 2020-06-09 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('login', models.CharField(blank=True, max_length=300)),
                ('password', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Company_info',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='balance.Company')),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('expenses', models.FloatField(blank=True, default=0, null=True)),
                ('payment', models.FloatField(blank=True, default=0, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
