# Generated by Django 3.0.6 on 2020-06-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_info',
            name='published_date',
        ),
    ]
