# Generated by Django 3.0.6 on 2020-06-23 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_remove_company_info_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('company_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='balance.Company_info')),
            ],
        ),
    ]
