# Generated by Django 3.0.6 on 2020-07-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_history_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_info',
            name='company_info',
        ),
        migrations.AddField(
            model_name='history_info',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='history_info',
            name='company_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history_info',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='history_info',
            name='expenses',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='history_info',
            name='payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
