# Generated by Django 3.0.6 on 2020-08-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_auto_20200731_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='expenses_limit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
