# Generated by Django 3.0.6 on 2020-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_company_info_expenses_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='key',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
