# Generated by Django 3.0.6 on 2020-08-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_auto_20200826_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_info',
            name='company_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
